WebApplicationASPMVC5/Models/Book.cs
namespace WebApplicationASPMVC5.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public int Price { get; set; }
    }
}

WebApplicationASPMVC5/Models/BookContext.cs
using System.Data.Entity;

namespace WebApplicationASPMVC5.Models
{
    public class BookContext : DbContext
    {
        public DbSet<Book> Books { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
    }
}

WebApplicationASPMVC5/Models/BookDbInitializer.cs
using System.Data.Entity;

namespace WebApplicationASPMVC5.Models
{
    public class BookDbInitializer : DropCreateDatabaseAlways<BookContext>
    {
        protected override void Seed(BookContext db)
        {
            db.Books.Add(new Book { Name = "Война и мир", Author = "Л. Толстой", Price = 220 });
            db.Books.Add(new Book { Name = "Отцы и дети", Author = "И. Тургенев", Price = 180 });
            db.Books.Add(new Book { Name = "Чайка", Author = "А. Чехов", Price = 150 });

            base.Seed(db);
        }
    }
}

WebApplicationASPMVC5/Models/Purchase.cs
using System;

namespace WebApplicationASPMVC5.Models
{
    public class Purchase
    {
        public int PurchaseId { get; set; }
        public string Person { get; set; }
        public string Address { get; set; }
        public int BookId { get; set; }
        public DateTime Date { get; set; }
    }
}

WebApplicationASPMVC5/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplicationASPMVC5.Models;

namespace WebApplicationASPMVC5.Controllers
{
    public class HomeController : Controller
    {
        BookContext db = new BookContext(); // создаем контекст данных

        public ActionResult Index()
        {            
            IEnumerable<Book> books = db.Books; // получаем из бд все объекты Book
            ViewBag.Books = books; // передаем все объекты в динамическое свойство Books в ViewBag            
            return View(); // возвращаем представление
        }

        [HttpGet]
        public ActionResult Buy(int id)
        {
            ViewBag.BookId = id;
            return View();
        }
        [HttpPost]
        public string Buy(Purchase purchase)
        {
            purchase.Date = DateTime.Now;
            db.Purchases.Add(purchase);
            db.SaveChanges();
            return "Спасибо," + purchase.Person + ", за покупку!";
        }
    }
}

WebApplicationASPMVC5/Controllers/ListController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplicationASPMVC5.Models;

namespace WebApplicationASPMVC5.Controllers
{
    public class ListController : Controller
    {
        BookContext db = new BookContext();

        public ActionResult Index()
        {
            IEnumerable<Purchase> purchases = db.Purchases;
            ViewBag.Purchases = purchases;
            return View();
        }
    }
}

WebApplicationASPMVC5/Views/Home/Buy.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3>Форма оформления покупки</h3>
    <form method="post" action="">
        <input type="hidden" value="@ViewBag.BookId" name="BookId" />
        <table>
            <tr>
                <td><p>Введите свое имя </p></td>
                <td><input type="text" name="Person" /> </td>
            </tr>
            <tr>
                <td><p>Введите адрес :</p></td>
                <td>
                    <input type="text" name="Address" />
                </td>
            </tr>
            <tr><td><input type="submit" value="Отправить" /> </td><td></td></tr>
        </table>
    </form>
</div>

WebApplicationASPMVC5/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h3>Распродажа книг</h3>
    <table>
        <tr class="header">
            <td><p>Название книги</p></td>
            <td><p>Автор</p></td>
            <td><p>Цена</p></td>
            <td></td>
        </tr>
        @foreach (var b in ViewBag.Books)
            {
            <tr>
                <td><p>@b.Name</p></td>
                <td><p>@b.Author</p></td>
                <td><p>@b.Price</p></td>
                <td><p><a href="/Home/Buy/@b.Id">Купить</a></p></td>
            </tr>
        }
    </table>
</div>

WebApplicationASPMVC5/Views/List/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h3>Список покупателей</h3>
    <table>
        <tr class=" = header">
            <td><p>Покупатель</p></td>
            <td><p>Адрес</p></td>
            <td><p>Дата</p></td>
        </tr>
        @foreach (var p in ViewBag.Purchases)
        {
            <tr>
                <td><p>@p.Person</p></td>
                <td><p>@p.Address</p></td>
                <td><p>@p.Date</p></td>
            </tr>
        }
    </table>
</div>

WebApplicationASPMVC5/Views/List/List.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <h3>Список покупателей</h3>
    <table>
        <tr class=" = header">
            <td><p>Покупатель</p></td>
            <td><p>Адрес</p></td>
            <td><p>Дата</p></td>
        </tr>
            @foreach(var b in ViewBag.Purchases)
            {
                <tr>
                    <td><p>@b.Person</p></td>
                    <td><p>b.Address</p></td>
                    <td><p>b.Date</p></td>
                </tr>
            }        
    </table>    
</div>

WebApplicationASPMVC5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <nav>
        <ul class="menu">
            <li>@Html.ActionLink("Главная", "Index", "Home")</li>
            <li>@Html.ActionLink("Список покупок", "Index", "List")</li>
        </ul>
    </nav>
    @RenderBody()
</body>
</html>